import pandas as pd

fal_data = [
    {
        "field_name": "record_id",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Probanden-ID",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_datum",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Datum",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "date_ymd",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alter",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Wie alt sind Sie? (Jahre)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "120",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_haendigkeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Sind Sie",
        "choices": "1, rechtshändig | 2, linkshändig | 3, beidhändig",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_geschlecht",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Geschlecht",
        "choices": "1, männlich | 2, weiblich | 3, anderes",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schulabschluss",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Welchen Schulabschluss haben Sie?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_taetigkeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Welcher Tätigkeit gehen Sie z.Zt. nach?",
        "choices": "1, Studium | 2, berufstätig | 3, nicht berufstätig",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studium_fachrichtung",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Fachrichtung (falls Studium)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_taetigkeit]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_beruf",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Beruf (falls berufstätig)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_taetigkeit]='2'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schlafdauer",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Wie viele Stunden haben Sie letzte Nacht geschlafen? (Stunden)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "24",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_schlafdauer_bewertung",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Diese Schlafdauer war für mich",
        "choices": "1, normal | 2, eher lang | 3, viel zu kurz, ich bin ziemlich müde",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alkohol",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Haben Sie gestern Alkohol getrunken?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_alkohol_menge",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte Menge angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_alkohol]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_raucher",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Falls Sie Raucher sind: Haben Sie heute",
        "choices": "1, sehr viel | 2, normal | 3, wenig / gar nicht geraucht",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_koffein",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Falls Sie Kaffee, Tee oder Cola trinken: Haben Sie heute",
        "choices": "1, sehr viel | 2, normal | 3, wenig/keine koffeinhaltigen Getränke getrunken",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_letzte_mahlzeit",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Vor wie vielen Stunden haben Sie zum letzten Mal gegessen?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "48",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Sind Sie z.Zt. in neurologischer, psychiatrischer oder psychologischer Behandlung?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_neuro]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_frueher",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Waren Sie bereits früher einmal in neurologischer, psychiatrischer oder psychologischer Behandlung?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_neuro_frueher_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_neuro_frueher]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_aerztlich",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Sind Sie z.Zt. in ärztlicher Behandlung (außer beim Neurologen/ Psychiater)?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_behandlung_aerztlich_grund",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, wegen",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_behandlung_aerztlich]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_medikamente",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Nehmen Sie z.Zt. Medikamente ein?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_medikamente_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_medikamente]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_drogen",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Nehmen Sie Drogen oder haben Sie schon mal regelmäßig Drogen genommen?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_drogen_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_drogen]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studien_mv",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Haben Sie bereits an Studien zur Bewegungsvorstellung teilgenommen?",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_studien_mv_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_studien_mv]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_mv_technik",
        "form_name": "fal",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Haben Sie bereits Bewegungsvorstellungstechniken genutzt, um eine Tätigkeit zu erlernen oder zu verbessern? (Sport, Instrumente o.ä.)",
        "choices": "0, Nein | 1, Ja",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_mv_technik_details",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Falls ja, bitte angeben",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[fal_mv_technik]='1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_instrument",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Spielen Sie ein Instrument? Wenn ja, welches? Wie lange schon? Wie oft spielen Sie in der Woche?",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "fal_sport",
        "form_name": "fal",
        "section_header": "",
        "field_type": "text",
        "field_label": "Treiben Sie regelmäßig Sport? Wenn ja, welche Sportarten? Wie lange schon? Wie oft betreibst Du diesen Sport in der Woche? (Bei Mehrfachantworten alles gesondert notieren!)",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
]

fal = pd.DataFrame(fal_data)

ehi_data = [
    {
        "field_name": "ehi_schreiben",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "1. Schreiben",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zeichnen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "2. Zeichnen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_werfen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "3. Werfen",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_schere",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "4. Schere",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_zahnbuerste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "5. Zahnbürste",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_messer",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "6. Messer (ohne Gabel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_loeffel",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "7. Löffel",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_besen",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "8. Besen (obere Hand)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_streichholz",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "9. Streichholz anzünden (Streichholz)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "ehi_kiste",
        "form_name": "edinburgh_handedness",
        "section_header": "",
        "field_type": "checkbox",
        "field_label": "10. Öffnen einer Kiste (Deckel)",
        "choices": "1, Links (1 Kreuz) | 2, Links (2 Kreuze) | 3, Rechts (1 Kreuz) | 4, Rechts (2 Kreuze) | 5, Beide gleich",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
]
ehi = pd.DataFrame(ehi_data)

# BDI-II item texts from the official German version (Kurzform, Beck et al. 1996)
bdi_ii_items = [
    "Ich bin nicht traurig. | Ich bin traurig. | Ich bin ständig traurig und kann mich nicht davon lösen. | Ich bin so traurig oder unglücklich, dass ich es nicht mehr aushalte.",
    "Ich sehe nicht besonders schwarz für die Zukunft. | Ich sehe schwarz für die Zukunft. | Ich fühle, dass nichts mehr gut werden kann. | Ich habe das Gefühl, dass meine Zukunft hoffnungslos ist und sich nichts bessern kann.",
    "Ich habe nicht das Gefühl, ein Versager zu sein. | Ich habe öfter das Gefühl, versagt zu haben. | Wenn ich auf mein Leben zurückblicke, sehe ich nur viele Misserfolge. | Ich habe das Gefühl, als völliger Versager zu sein.",
    "Ich bin mit mir und meinem Leben zufrieden. | Ich bin nicht mehr so zufrieden wie früher. | Ich bin mit mir und meinem Leben unzufrieden. | Ich bin völlig unzufrieden mit mir und meinem Leben.",
    "Ich fühle mich nicht besonders schuldig. | Ich fühle mich öfter schuldig. | Ich fühle mich die meiste Zeit schuldig. | Ich fühle mich ständig schuldig.",
    "Ich fühle mich nicht bestraft. | Ich fühle mich manchmal bestraft. | Ich fühle mich oft bestraft. | Ich fühle mich ständig bestraft.",
    "Ich bin mit mir selbst zufrieden. | Ich bin mit mir selbst unzufrieden. | Ich verachte mich selbst. | Ich hasse mich selbst.",
    "Ich kritisiere mich nicht mehr als sonst. | Ich kritisiere mich mehr als früher. | Ich kritisiere mich ständig. | Ich kritisiere mich für alles, was ich tue.",
    "Ich habe keine Selbstmordgedanken. | Ich habe manchmal Selbstmordgedanken, würde sie aber nicht ausführen. | Ich habe öfter Selbstmordgedanken. | Ich würde mich am liebsten umbringen, wenn ich die Gelegenheit hätte.",
    "Ich weine nicht mehr als sonst. | Ich weine jetzt öfter als früher. | Ich weine jetzt ständig. | Früher konnte ich weinen, jetzt kann ich es nicht mehr, auch wenn ich möchte.",
    "Ich bin nicht unruhiger als sonst. | Ich bin manchmal unruhig oder nervös. | Ich bin oft unruhig oder nervös. | Ich bin ständig unruhig oder nervös.",
    "Ich habe mein Interesse an anderen Menschen oder Aktivitäten nicht verloren. | Ich habe weniger Interesse an anderen Menschen oder Aktivitäten als früher. | Ich habe fast alles Interesse an anderen Menschen oder Aktivitäten verloren. | Ich habe das Interesse an anderen Menschen oder Aktivitäten völlig verloren.",
    "Ich kann Entscheidungen genauso gut treffen wie früher. | Ich habe mehr Schwierigkeiten, Entscheidungen zu treffen als früher. | Ich habe große Schwierigkeiten, Entscheidungen zu treffen. | Ich kann überhaupt keine Entscheidungen mehr treffen.",
    "Ich fühle mich nicht wertlos. | Ich fühle mich weniger wertvoll als früher. | Ich fühle mich wertlos. | Ich fühle mich völlig wertlos.",
    "Ich habe genauso viel Energie wie früher. | Ich habe weniger Energie als früher. | Ich habe viel weniger Energie als früher. | Ich habe überhaupt keine Energie mehr.",
    "Ich habe keine Schlafprobleme. | Ich schlafe schlechter als früher. | Ich wache nachts oft auf und habe Schwierigkeiten, wieder einzuschlafen. | Ich kann kaum noch schlafen.",
    "Ich bin nicht reizbarer als sonst. | Ich bin leichter reizbar als früher. | Ich bin viel reizbarer als früher. | Ich bin ständig gereizt.",
    "Mein Appetit ist nicht schlechter als sonst. | Mein Appetit ist schlechter als früher. | Mein Appetit ist jetzt viel schlechter. | Ich habe überhaupt keinen Appetit mehr.",
    "Ich kann mich genauso gut konzentrieren wie früher. | Ich kann mich nicht mehr so gut konzentrieren wie früher. | Ich habe große Schwierigkeiten, mich zu konzentrieren. | Ich kann mich überhaupt nicht mehr konzentrieren.",
    "Ich bin nicht müder oder erschöpfter als sonst. | Ich bin schneller müde oder erschöpft als früher. | Ich bin fast immer müde oder erschöpft. | Ich bin ständig müde oder erschöpft.",
    "Ich habe mein Interesse an Sexualität nicht verloren. | Ich habe weniger Interesse an Sexualität als früher. | Ich habe fast alles Interesse an Sexualität verloren. | Ich habe das Interesse an Sexualität völlig verloren."
]

bdi_ii_item_names = [
    "Traurigkeit",
    "Pessimismus",
    "Versagensgefühle",
    "Unzufriedenheit",
    "Schuldgefühle",
    "Gefühle von Bestrafung",
    "Selbstablehnung",
    "Selbstkritik",
    "Suizidgedanken oder -wünsche",
    "Weinen",
    "Unruhe",
    "Verlust von Interesse",
    "Entscheidungsschwierigkeiten",
    "Wertlosigkeitsgefühle",
    "Verlust von Energie",
    "Schlafstörungen",
    "Reizbarkeit",
    "Veränderungen des Appetits",
    "Konzentrationsschwierigkeiten",
    "Müdigkeit oder Erschöpfung",
    "Verlust des Interesses an Sexualität"
]

bdi_ii_data = [
    {
        "field_name": f"bdi_ii_{i+1}_{bdi_ii_item_names[i].lower().replace(' ', '_')}",
        "form_name": "bdi_ii",
        "section_header": "",
        "field_type": "radio",
        "field_label": f"{i+1}.",
        "choices": " | ".join([f"{j}, {option}" for j, option in enumerate(item.split(" | "))]),
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": str(i+1),
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
    for i, item in enumerate(bdi_ii_items)
]
bdi_ii = pd.DataFrame(bdi_ii_data)

moca_data = [
    {
        "field_name": "moca_trails",
        "form_name": "moca",
        "section_header": "Visuospatial/Executive",
        "field_type": "text",
        "field_label": "Trail Making Test",
        "choices": "",
        "field_note": "Patient draws a line going from 1 to A, then to 2, then to B and so on. Score: 1 point if correctly executed.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "1",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "1",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_cube",
        "form_name": "moca",
        "section_header": "",
        "field_type": "text",
        "field_label": "Copy Cube",
        "choices": "",
        "field_note": "Score: 1 point for correctly executed drawing.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "1",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "2",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_clock",
        "form_name": "moca",
        "section_header": "",
        "field_type": "text",
        "field_label": "Draw Clock (Ten past eleven)",
        "choices": "",
        "field_note": "Score: 1 point for each of the following: Contour (1), Numbers (1), Hands (1)",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "3",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "3",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_naming",
        "form_name": "moca",
        "section_header": "Naming",
        "field_type": "text",
        "field_label": "Naming animals",
        "choices": "",
        "field_note": "Score: 1 point for each correctly identified picture (lion, rhinoceros/rhino, camel/dromedary)",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "3",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "4",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_memory",
        "form_name": "moca",
        "section_header": "Memory",
        "field_type": "text",
        "field_label": "Recall",
        "choices": "",
        "field_note": "No points assigned for immediate recall. Score: 1 point for each word recalled without cues.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "5",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "5",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_digits",
        "form_name": "moca",
        "section_header": "Attention",
        "field_type": "text",
        "field_label": "Digit Span",
        "choices": "",
        "field_note": "Score: 1 point for each correctly repeated sequence (forward: 2-1-8-5-4, backward: 7-4-2)",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "2",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "6",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_letter_a",
        "form_name": "moca",
        "section_header": "",
        "field_type": "text",
        "field_label": "Letter A",
        "choices": "",
        "field_note": "Score: 1 point if 1 error or less (tapping when hearing the letter A)",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "1",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "7",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_serial_7",
        "form_name": "moca",
        "section_header": "",
        "field_type": "text",
        "field_label": "Serial 7 subtraction",
        "choices": "",
        "field_note": "Score: 1 point for each correct subtraction. Max 3 points.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "3",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "8",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_repetition",
        "form_name": "moca",
        "section_header": "Language",
        "field_type": "text",
        "field_label": "Sentence Repetition",
        "choices": "",
        "field_note": "Score: 1 point for each correctly repeated sentence.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "2",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "9",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_fluency",
        "form_name": "moca",
        "section_header": "",
        "field_type": "text",
        "field_label": "Verbal Fluency",
        "choices": "",
        "field_note": "Score: 1 point if 11 words or more in 60 seconds.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "1",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "10",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_abstraction",
        "form_name": "moca",
        "section_header": "Abstraction",
        "field_type": "text",
        "field_label": "Similarities",
        "choices": "",
        "field_note": "Score: 1 point for each correct pair.",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "2",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "11",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_orientation",
        "form_name": "moca",
        "section_header": "Orientation",
        "field_type": "text",
        "field_label": "Time and Place",
        "choices": "",
        "field_note": "Score: 1 point for each correct answer (Date, Month, Year, Day, Place, City).",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "6",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "12",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_education",
        "form_name": "moca",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Education Adjustment",
        "choices": "0, ≥ 12 years of education | 1, < 12 years of education",
        "field_note": "Add 1 point if ≤12 years of education",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "13",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "moca_total_score",
        "form_name": "moca",
        "section_header": "",
        "field_type": "calc",
        "field_label": "TOTAL SCORE",
        "choices": "[moca_trails] + [moca_cube] + [moca_clock] + [moca_naming] + [moca_memory] + [moca_digits] + [moca_letter_a] + [moca_serial_7] + [moca_repetition] + [moca_fluency] + [moca_abstraction] + [moca_orientation] + [moca_education]",
        "field_note": "0-30; +1 point if ≤ 12 years of education",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
]
moca = pd.DataFrame(moca_data)

tmt_data = [
    {
        "field_name": "tmt_a_time",
        "form_name": "tmt",
        "section_header": "",
        "field_type": "text",
        "field_label": "TMT A Time",
        "choices": "",
        "field_note": "time to complete in seconds",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "tmt_a_errors",
        "form_name": "tmt",
        "section_header": "",
        "field_type": "text",
        "field_label": "TMT A Errors",
        "choices": "",
        "field_note": "total amount of errors",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "tmt_b_time",
        "form_name": "tmt",
        "section_header": "",
        "field_type": "text",
        "field_label": "TMT B Time",
        "choices": "",
        "field_note": "time to complete in seconds",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "tmt_b_errors",
        "form_name": "tmt",
        "section_header": "",
        "field_type": "text",
        "field_label": "TMT B Errors",
        "choices": "",
        "field_note": "total amount of errors",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
]

tmt = pd.DataFrame(tmt_data)

# Weinstein's Noise Sensitivity Scale (WNSS-21)
# Worthington, Debra L. ‘Weinstein Noise Sensitivity Scale (WNSS): (Weinstein, 1978)’. In The Sourcebook of Listening Research, 1st edn, edited by Debra L. Worthington and Graham D. Bodie. Wiley, 2017. https://doi.org/10.1002/9781119102991.ch52.
wnss_data = [
    {
        "field_name": "wnss_instructions",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "descriptive",
        "field_label": "Below are a number of statements addressing individual reactions to noise. After reading each statement, please select the number that best represents your level of agreement with the statement. Rating Scale: 1 = Strongly Disagree, 5 = Strongly Agree",
        "choices": "",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_1",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "1) I wouldn't mind living on a noisy street if the apartment I had was nice.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_2",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "2) I am more aware of noise than I used to be.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_3",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "3) No one should mind much if someone turns up his or her stereo full blast once in a while.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_4",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "4) At movies, whispering and crinkling candy wrappers disturb me.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_5",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "5) I am easily awakened by noise.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_6",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "6) If it's noisy where I'm studying, I try to close the door or window or move someplace else.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_7",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "7) I get annoyed when my neighbors are noisy.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_8",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "8) I get used to most noises without much difficulty.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_9",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "9) It would matter to me if an apartment I was interested in renting were located across from a fire station.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_10",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "10) Sometimes noises get on my nerves and get me irritated.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_11",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "11) Even music I normally like will bother me if I'm trying to concentrate.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_12",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "12) It wouldn't bother me to hear the sounds of everyday living from neighbors (footsteps, running water, etc.).",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_13",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "13) When I want to be alone, it disturbs me to hear outside noises.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_14",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "14) I'm good at concentrating no matter what is going on around me.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_15",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "15) In a library, I don't mind if people carry on a conversation if they do it quietly.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_16",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "16) There are often times when I want complete silence.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_17",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "17) Motorcycles ought to be required to have bigger mufflers.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_18",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "18) I find it hard to relax in a place that's noisy.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_19",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "19) I get mad at people who make noise that keeps me from falling asleep or getting work done.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_20",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "20) I wouldn't mind living in an apartment with thin walls.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    },
    {
        "field_name": "wnss_21",
        "form_name": "wnss",
        "section_header": "",
        "field_type": "radio",
        "field_label": "21) I am sensitive to noise.",
        "choices": "1, 1 - Strongly Disagree | 2, 2 | 3, 3 | 4, 4 | 5, 5 - Strongly Agree",
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": ""
    }
]

wnss = pd.DataFrame(wnss_data)



